//! # Planets Section - Quiz System with 50 Real Questions
//!
//! Provides 50 authentic multiple-choice questions about planets and space,
//! with real scientific facts, true options, and a scoring system.

use serde::{Deserialize, Serialize};

/// A single quiz question about planets.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct QuizQuestion {
    pub id: u32,
    pub question: &'static str,
    pub options: [&'static str; 4],
    pub correct_index: usize,
    pub explanation: &'static str,
    pub difficulty: QuizDifficulty,
}

/// Difficulty level for quiz questions.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Serialize, Deserialize)]
pub enum QuizDifficulty {
    Easy,
    Medium,
    Hard,
    Expert,
}

impl QuizDifficulty {
    pub fn label(self) -> &'static str {
        match self {
            QuizDifficulty::Easy => "⭐ Easy",
            QuizDifficulty::Medium => "⭐⭐ Medium",
            QuizDifficulty::Hard => "⭐⭐⭐ Hard",
            QuizDifficulty::Expert => "⭐⭐⭐⭐ Expert",
        }
    }
    
    pub fn points(self) -> u32 {
        match self {
            QuizDifficulty::Easy => 10,
            QuizDifficulty::Medium => 25,
            QuizDifficulty::Hard => 50,
            QuizDifficulty::Expert => 100,
        }
    }
}

/// Collection of all 50 quiz questions about planets.
pub fn get_all_planet_questions() -> Vec<QuizQuestion> {
    vec![
        // === EASY QUESTIONS (1-15) ===
        QuizQuestion {
            id: 1,
            question: "What is the largest planet in our solar system?",
            options: ["Saturn", "Jupiter", "Neptune", "Uranus"],
            correct_index: 1,
            explanation: "Jupiter is the largest planet with a diameter of 139,820 km - 11 times wider than Earth! Its Great Red Spot is a storm larger than our entire planet.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 2,
            question: "Which planet is known as the Red Planet?",
            options: ["Venus", "Mars", "Mercury", "Jupiter"],
            correct_index: 1,
            explanation: "Mars gets its reddish color from iron oxide (rust) on its surface. It has the tallest volcano in the solar system - Olympus Mons at 21 km high!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 3,
            question: "Which planet is closest to the Sun?",
            options: ["Venus", "Earth", "Mercury", "Mars"],
            correct_index: 2,
            explanation: "Mercury orbits at just 57.9 million km from the Sun. A year there is only 88 Earth days long, and surface temperatures range from -173°C to 427°C!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 4,
            question: "How many planets are in our solar system?",
            options: ["7", "8", "9", "10"],
            correct_index: 1,
            explanation: "There are 8 planets in our solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Pluto was reclassified as a dwarf planet in 2006.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 5,
            question: "Which planet has the most moons?",
            options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
            correct_index: 1,
            explanation: "Saturn has at least 82 known moons! Its largest moon Titan has a thick atmosphere and liquid methane lakes on its surface.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 6,
            question: "What are Saturn's rings made of?",
            options: ["Solid metal", "Ice and rock particles", "Gas clouds", "Liquid water"],
            correct_index: 1,
            explanation: "Saturn's rings are made of billions of ice and rock particles ranging from tiny grains to chunks as big as mountains. They span 282,000 km but are only about 10 meters thick!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 7,
            question: "Which planet is known as Earth's 'Twin'?",
            options: ["Mars", "Mercury", "Venus", "Neptune"],
            correct_index: 2,
            explanation: "Venus is called Earth's twin because of its similar size (95% of Earth's diameter) and mass. However, its surface temperature reaches 465°C - hot enough to melt lead!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 8,
            question: "What is the smallest planet in our solar system?",
            options: ["Mercury", "Mars", "Venus", "Pluto"],
            correct_index: 0,
            explanation: "Mercury is the smallest planet at just 4,879 km in diameter. It's actually smaller than Jupiter's moon Ganymede and Saturn's moon Titan!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 9,
            question: "How long does it take Earth to orbit the Sun?",
            options: ["300 days", "365 days", "400 days", "330 days"],
            correct_index: 1,
            explanation: "Earth takes approximately 365.25 days to complete one orbit. That's why we add an extra day every 4 years - Leap Year!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 10,
            question: "Which planet has a Great Red Spot?",
            options: ["Saturn", "Mars", "Jupiter", "Neptune"],
            correct_index: 2,
            explanation: "Jupiter's Great Red Spot is a massive storm that has been raging for at least 350 years. It's about 1.3 times the diameter of Earth!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 11,
            question: "What is the hottest planet in our solar system?",
            options: ["Mercury", "Venus", "Mars", "Jupiter"],
            correct_index: 1,
            explanation: "Venus is hotter than Mercury despite being further from the Sun! Its thick CO2 atmosphere creates a runaway greenhouse effect, trapping heat and reaching 465°C.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 12,
            question: "Which planet is farthest from the Sun?",
            options: ["Uranus", "Saturn", "Neptune", "Pluto"],
            correct_index: 2,
            explanation: "Neptune is the farthest planet at 4.5 billion km from the Sun. It takes 165 Earth years to complete one orbit!",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 13,
            question: "What color is Mars' sky during sunset?",
            options: ["Red", "Blue", "Green", "Purple"],
            correct_index: 1,
            explanation: "Mars' sky appears blue during sunset, opposite to Earth's red sunsets! This is due to the way Mars' thin, dusty atmosphere scatters sunlight.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 14,
            question: "Which planet rotates on its side?",
            options: ["Neptune", "Uranus", "Saturn", "Jupiter"],
            correct_index: 1,
            explanation: "Uranus rotates at an extreme 98-degree tilt, essentially rolling on its side! This gives it extreme seasons with 42-year-long days and nights.",
            difficulty: QuizDifficulty::Easy,
        },
        QuizQuestion {
            id: 15,
            question: "What is Earth's atmosphere mostly made of?",
            options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
            correct_index: 2,
            explanation: "Earth's atmosphere is 78% nitrogen and only 21% oxygen. The remaining 1% includes argon, carbon dioxide, and other trace gases.",
            difficulty: QuizDifficulty::Easy,
        },
        // === MEDIUM QUESTIONS (16-30) ===
        QuizQuestion {
            id: 16,
            question: "How long is a day on Venus in Earth days?",
            options: ["24 hours", "48 hours", "243 Earth days", "117 Earth days"],
            correct_index: 2,
            explanation: "Venus takes 243 Earth days to rotate once, making its day longer than its year (225 Earth days)! It also rotates backwards compared to most planets.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 17,
            question: "Which planet has the strongest winds?",
            options: ["Jupiter", "Saturn", "Neptune", "Earth"],
            correct_index: 2,
            explanation: "Neptune has the strongest winds in the solar system, reaching an incredible 2,100 km/h! That's more than 2.5 times faster than the strongest tornado on Earth.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 18,
            question: "What is the largest moon in the solar system?",
            options: ["Earth's Moon", "Titan (Saturn)", "Ganymede (Jupiter)", "Io (Jupiter)"],
            correct_index: 2,
            explanation: "Ganymede is the largest moon at 5,268 km in diameter - larger than Mercury! It's the only moon with its own magnetic field.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 19,
            question: "How many Earths could fit inside Jupiter?",
            options: ["100", "500", "1,300", "10,000"],
            correct_index: 2,
            explanation: "Jupiter's volume is so massive that about 1,300 Earths could fit inside it! Despite its size, it has the shortest day of any planet - just under 10 hours.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 20,
            question: "Which planet has the highest mountain?",
            options: ["Earth", "Mars", "Venus", "Jupiter's moon Io"],
            correct_index: 1,
            explanation: "Olympus Mons on Mars is the tallest mountain at 21.9 km high - nearly 2.5 times taller than Mount Everest! It's a shield volcano the size of Arizona.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 21,
            question: "What causes Uranus' blue-green color?",
            options: ["Water oceans", "Methane in atmosphere", "Copper minerals", "Alien plants"],
            correct_index: 1,
            explanation: "Methane gas in Uranus' atmosphere absorbs red light and reflects blue-green light, giving the planet its distinctive cyan color.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 22,
            question: "Which planet has the most volcanoes?",
            options: ["Earth", "Mars", "Venus", "Io (Jupiter's moon)"],
            correct_index: 2,
            explanation: "Venus has over 1,600 known volcanoes, more than any other planet! Its surface is covered with volcanic features, and some may still be active.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 23,
            question: "What is the temperature range on Mercury?",
            options: ["-50°C to 50°C", "-173°C to 427°C", "-100°C to 200°C", "-200°C to 100°C"],
            correct_index: 1,
            explanation: "Mercury experiences the most extreme temperature swings of any planet: -173°C at night to 427°C during the day, a 600°C difference!",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 24,
            question: "How deep is Jupiter's Great Red Spot?",
            options: ["100 km", "500 km", "300-500 km deep", "It's shallow"],
            correct_index: 2,
            explanation: "Jupiter's Great Red Spot extends 300-500 km deep into the atmosphere, much deeper than scientists previously thought!",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 25,
            question: "Which planet has ice that is hotter than boiling water?",
            options: ["Uranus", "Neptune", "An exoplanet", "Mercury"],
            correct_index: 0,
            explanation: "Uranus has a type of 'hot ice' that forms under extreme pressure in its mantle. Despite being called ice, it's actually hotter than boiling water!",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 26,
            question: "What percentage of the solar system's mass is in the Sun?",
            options: ["75%", "99.86%", "50%", "95%"],
            correct_index: 1,
            explanation: "The Sun contains 99.86% of the solar system's mass! All planets, moons, asteroids, and comets combined make up just 0.14% of the remaining mass.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 27,
            question: "Which planet is the only one known to have liquid water on its surface?",
            options: ["Mars", "Earth", "Europa (Jupiter's moon)", "Enceladus (Saturn's moon)"],
            correct_index: 1,
            explanation: "Earth is currently the only known planet with stable liquid water on its surface. 71% of Earth's surface is covered in water - that's why it's called the Blue Marble!",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 28,
            question: "What is unique about Neptune's orbit?",
            options: ["It's perfectly circular", "It's farther from the Sun than Pluto sometimes", "It's the fastest orbit", "It's tidally locked"],
            correct_index: 1,
            explanation: "Pluto's highly elliptical orbit sometimes brings it closer to the Sun than Neptune. However, Neptune will never collide with Pluto due to orbital resonance!",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 29,
            question: "What is Saturn's moon Titan known for?",
            options: ["Ice volcanoes", "Liquid methane lakes", "Oxygen atmosphere", "Active plate tectonics"],
            correct_index: 1,
            explanation: "Titan has stable liquid methane and ethane lakes on its surface, making it the only moon with liquid on its surface! Its atmosphere is thicker than Earth's.",
            difficulty: QuizDifficulty::Medium,
        },
        QuizQuestion {
            id: 30,
            question: "Which planet has a hexagonal storm at its north pole?",
            options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
            correct_index: 1,
            explanation: "Saturn has a mysterious hexagonal (six-sided) storm at its north pole that's about 32,000 km across - big enough to fit four Earths inside!",
            difficulty: QuizDifficulty::Medium,
        },
        // === HARD QUESTIONS (31-45) ===
        QuizQuestion {
            id: 31,
            question: "What is the core temperature of Jupiter?",
            options: ["5,000°C", "24,000°C", "35,000°C", "100,000°C"],
            correct_index: 1,
            explanation: "Jupiter's core reaches about 24,000°C - hotter than the surface of the Sun! This heat is leftover from its formation and powers its massive storms.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 32,
            question: "How many times has Pluto completed an orbit since its discovery in 1930?",
            options: ["10 times", "3 times", "Less than once", "15 times"],
            correct_index: 2,
            explanation: "Pluto has completed less than one full orbit since its discovery! Its 248-year orbit means it won't finish one complete trip around the Sun until 2178.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 33,
            question: "What is the escape velocity needed to leave Jupiter's gravity?",
            options: ["11.2 km/s", "24.8 km/s", "59.5 km/s", "100 km/s"],
            correct_index: 2,
            explanation: "Jupiter's escape velocity is 59.5 km/s (213,000 km/h) compared to Earth's 11.2 km/s (40,320 km/h). That's why probes need massive gravity assists to explore the outer system!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 34,
            question: "Which planet has the most elliptical (eccentric) orbit?",
            options: ["Mercury", "Mars", "Pluto", "Neptune"],
            correct_index: 0,
            explanation: "Mercury has the most eccentric orbit of any planet, varying from 46 million km to 70 million km from the Sun! This causes large variations in its speed and temperature.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 35,
            question: "What causes the 'Sulfur Dioxide Snow' on Venus' mountains?",
            options: ["Volcanic eruptions", "Atmospheric chemistry", "Solar wind", "Meteor impacts"],
            correct_index: 1,
            explanation: "Venus' atmospheric chemistry creates sulfur dioxide 'snow' that falls on its highest mountain peaks, similar to how water snow falls on Earth's mountains!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 36,
            question: "How much would a 70 kg person weigh on Saturn?",
            options: ["30 kg", "74.5 kg", "70 kg", "120 kg"],
            correct_index: 1,
            explanation: "While Saturn is much larger than Earth, its gravity is only 10.44 m/s² (compared to Earth's 9.8). A 70 kg person would feel like 74.5 kg!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 37,
            question: "What is the largest known canyon in the solar system?",
            options: ["Grand Canyon (Earth)", "Valles Marineris (Mars)", "Ithaca Chasma (Tethys)", "Verdun (Moon)"],
            correct_index: 1,
            explanation: "Valles Marineris on Mars stretches 4,000 km long, 200 km wide, and 7 km deep - that's 10 times longer and 5 times deeper than the Grand Canyon!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 38,
            question: "Which moon has a subsurface ocean that may harbor life?",
            options: ["All of these", "Europa (Jupiter)", "Enceladus (Saturn)", "Ganymede (Jupiter)"],
            correct_index: 0,
            explanation: "Multiple moons (Europa, Enceladus, and Ganymede) have strong evidence of subsurface liquid water oceans, making them prime targets in the search for extraterrestrial life!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 39,
            question: "How fast does a day on Jupiter pass in Earth hours?",
            options: ["24 hours", "16 hours", "9.93 hours", "5 hours"],
            correct_index: 2,
            explanation: "Despite being the largest planet, Jupiter has the fastest rotation at just 9 hours and 55 minutes per day! This rapid spin causes its noticeable equatorial bulge.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 40,
            question: "What is the atmospheric pressure on Venus in Earth atmospheres?",
            options: ["2 atm", "10 atm", "92 atm", "500 atm"],
            correct_index: 2,
            explanation: "Venus' surface pressure is 92 times Earth's - equivalent to being 900 meters underwater on Earth! This would crush any spacecraft not specifically designed for it.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 41,
            question: "Which planet occasionally appears to move backwards (retrograde) from Earth?",
            options: ["All of them", "Only Mercury and Venus", "Only Mars", "Only the outer planets"],
            correct_index: 0,
            explanation: "All planets exhibit apparent retrograde motion as Earth overtakes them in orbit. Mars' retrograde loops are particularly noticeable and helped early astronomers understand the solar system!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 42,
            question: "What is the composition of Saturn's moon Enceladus' geysers?",
            options: ["Methane", "Water ice and organic compounds", "Liquid nitrogen", "Sulfur dioxide"],
            correct_index: 1,
            explanation: "Enceladus' geysers shoot water ice, organic compounds, and salts hundreds of kilometers into space! This proves the existence of a subsurface liquid ocean with potential for life.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 43,
            question: "Which planet has the thinnest atmosphere?",
            options: ["Mercury", "Mars", "Pluto", "Neptune"],
            correct_index: 0,
            explanation: "Mercury has virtually no atmosphere - just a tiny exosphere of atoms blasted off its surface by the solar wind. This is why temperatures vary so dramatically.",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 44,
            question: "What is the estimated number of galaxies in the observable universe?",
            options: ["100 billion", "2 trillion", "500 billion", "10 billion"],
            correct_index: 1,
            explanation: "The Hubble Space Telescope estimates there are about 2 trillion galaxies in the observable universe. That's 10 times more than previously thought!",
            difficulty: QuizDifficulty::Hard,
        },
        QuizQuestion {
            id: 45,
            question: "What is the approximate age of our solar system?",
            options: ["4.6 billion years", "6 billion years", "3.5 billion years", "10 billion years"],
            correct_index: 0,
            explanation: "Our solar system formed about 4.6 billion years ago from a giant molecular cloud. The oldest known meteorite samples date back to this time.",
            difficulty: QuizDifficulty::Hard,
        },
        // === EXPERT QUESTIONS (46-50) ===
        QuizQuestion {
            id: 46,
            question: "What is the Bond albedo of Venus and how does it affect its temperature?",
            options: ["0.1 - absorbs most light, cooler", "0.75 - reflects most light, but greenhouse effect makes it hotter", "0.5 - balanced", "1.0 - perfect reflector, cold"],
            correct_index: 1,
            explanation: "Venus has a Bond albedo of 0.75 (reflects 75% of sunlight), yet its surface is the hottest in the solar system at 465°C due to its extreme greenhouse effect! This makes it a fascinating climate study.",
            difficulty: QuizDifficulty::Expert,
        },
        QuizQuestion {
            id: 47,
            question: "What phenomenon creates Jupiter's radiation belts, the most dangerous in the solar system?",
            options: ["Solar winds directly hitting the planet", "Volcanic eruptions from Io interacting with Jupiter's magnetic field", "Cosmic rays trapped by atmosphere", "Nuclear reactions in the core"],
            correct_index: 1,
            explanation: "Jupiter's powerful magnetic field accelerates particles from Io's volcanic eruptions, creating radiation belts 10,000 times more intense than Earth's Van Allen belts! Europa Clipper had to be heavily shielded.",
            difficulty: QuizDifficulty::Expert,
        },
        QuizQuestion {
            id: 48,
            question: "How does Saturn's moon Titan maintain a thick atmosphere while other moons cannot?",
            options: ["It's the only moon with a magnetic field", "Its low gravity and low temperature trap methane and nitrogen, while cold traps prevent escape", "It has active volcanoes constantly replenishing gas", "Solar wind keeps compressing gas onto the surface"],
            correct_index: 1,
            explanation: "Titan's atmosphere (1.5x Earth's pressure) is maintained by its extreme cold (-179°C) which slows gas escape, combined with constant replenishment from methane lakes and subsurface processes.",
            difficulty: QuizDifficulty::Expert,
        },
        QuizQuestion {
            id: 49,
            question: "What unique geological process shapes the surface of Jupiter's moon Io?",
            options: ["Plate tectonics like Earth", "Tidal heating from Jupiter's gravity creating over 400 active volcanoes", "Erosion from liquid water", "Wind erosion from thin atmosphere"],
            correct_index: 1,
            explanation: "Io is the most volcanically active body in the solar system with over 400 volcanoes! Tidal flexing from Jupiter's immense gravity generates heat that powers constant eruptions, reshaping its surface continuously.",
            difficulty: QuizDifficulty::Expert,
        },
        QuizQuestion {
            id: 50,
            question: "How do scientists measure the internal structure of planets without being there?",
            options: ["X-ray imaging", "Seismology, gravity field measurements, and magnetic field analysis combined with computer modeling", "Drilling through crust from orbit", "Temperature readings only"],
            correct_index: 1,
            explanation: "Scientists combine multiple techniques: seismic waves (from quakes), gravitational field mapping (revealing density variations), magnetic field analysis, and computer modeling to create detailed planetary interior maps.",
            difficulty: QuizDifficulty::Expert,
        },
    ]
}